# Simple Azure DevOps Pipeline for Node.js with Self-Hosted Environment

trigger:
  branches:
    include:
      - '*'  # Disable triggers for direct branch pushes

pr:
  branches:
    include:
      - main  # Runs pipeline on PRs targeting the 'main' branch

# Specify the custom self-hosted agent pool 

jobs:
- job: BuildJob
  displayName: 'Build the Node.js Application'
  
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Specify Node.js version; adjust as needed for your app

  - checkout: self  # Checks out the code from the repo

  - script: echo hello;npm install
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build the application'
